# Generated by Django 3.1 on 2020-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('memo', models.CharField(max_length=200)),
                ('selectType', models.CharField(default='Django', max_length=20)),
            ],
        ),
    ]
